### ISSUE TITLE
fix image compress problem

### ISSUE THREAD

**Issue by nighca** [Front-End-Engineering-Cloud/builder#84]
图片压缩功能貌似不太稳定，先默认配置不打开吧

```
[2018-06-22 09:49:20.943] [ERROR] FEC - generate failed
[2018-06-22 09:49:20.945] [ERROR] FEC - ./src/common/components/PlatformIcon/os_icons.png
Module build failed: Error: Command failed: /fec/node_modules/pngquant-bin/vendor/pngquant --output /tmp/5b6970ef-49bc-495f-bc6f-b2e965156891 /tmp/81115384-6e34-4b75-b67b-4c5262ce671c --quality 65-90 --speed 4

    at Promise.all.then.arr (/fec/node_modules/exec-buffer/node_modules/execa/index.js:201:11)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/common/components/PlatformIcon/index.tsx 9:16-41
 @ ./src/vm/components/TableItems/ImageItems.tsx
 @ ./src/vm/components/TableItems/index.ts
 @ ./src/vm/containers/BsnList/index.tsx
 @ ./src/vm/routes.ts
 @ ./src/vm/index.tsx
 @ ./src/routes.ts
 @ ./src/index.tsx
```

**Comment by nighca** [comment]
https://github.com/Front-End-Engineering-Cloud/builder/releases/tag/v1.9.0
